---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
    - port: 14268
      name: http-collector
    - port: 16686
      name: http-ui
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: dzlabacr01.azurecr.io/jaegertracing/all-in-one:1.6
          ports:
            - containerPort: 14268
            - containerPort: 16686